// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyDd2sMbmMw0Cgo4tbKE2eXSXl0ThtBG-Y4",
    appId: '1:631868110269:ios:b5b1f4b6b9badda3054ed4',
    messagingSenderId: "631868110269",
    projectId: "focusapp-enhanced",
    storageBucket: "focusapp-enhanced.firebasestorage.app",
    iosBundleId: 'com.example.groupprojectGroup5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
      apiKey: "AIzaSyDd2sMbmMw0Cgo4tbKE2eXSXl0ThtBG-Y4",
      authDomain: "focusapp-enhanced.firebaseapp.com",
      projectId: "focusapp-enhanced",
      storageBucket: "focusapp-enhanced.firebasestorage.app",
      messagingSenderId: "631868110269",
      appId: "1:631868110269:web:c65ea5acf68f6176054ed4",
      measurementId: "G-MN0152Y00R"
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDd2sMbmMw0Cgo4tbKE2eXSXl0ThtBG-Y4",
      authDomain: "focusapp-enhanced.firebaseapp.com",
      projectId: "focusapp-enhanced",
      storageBucket: "focusapp-enhanced.firebasestorage.app",
      messagingSenderId: "631868110269",
      appId: "1:631868110269:web:c65ea5acf68f6176054ed4",
      measurementId: "G-MN0152Y00R"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyDd2sMbmMw0Cgo4tbKE2eXSXl0ThtBG-Y4",
    appId: '1:631868110269:ios:b5b1f4b6b9badda3054ed4',
    messagingSenderId: "631868110269",
    projectId: "focusapp-enhanced",
    storageBucket: "focusapp-enhanced.firebasestorage.app",
    iosBundleId: 'com.example.groupprojectGroup5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDd2sMbmMw0Cgo4tbKE2eXSXl0ThtBG-Y4",
    appId: "1:631868110269:android:32f4221ff90da435054ed4",
    messagingSenderId: "631868110269",
    measurementId: "G-MN0152Y00R",
    projectId: "focusapp-enhanced",
    storageBucket: "focusapp-enhanced.firebasestorage.app",
  );

}