// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtF-xEiGRU44NdkiRowx-b1RS7iki2P18',
    appId: '1:679860095960:ios:254dadb5bf83acc9ddc0ad',
    messagingSenderId: '679860095960',
    projectId: 'groupproject-group5-a80a2',
    storageBucket: 'groupproject-group5-a80a2.firebasestorage.app',
    iosBundleId: 'com.example.groupprojectGroup5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA24F_Pjz5TrftBkIooxl8GnmjTfdqZpG8',
    appId: '1:679860095960:web:7ebde336c7121669ddc0ad',
    messagingSenderId: '679860095960',
    projectId: 'groupproject-group5-a80a2',
    authDomain: 'groupproject-group5-a80a2.firebaseapp.com',
    storageBucket: 'groupproject-group5-a80a2.firebasestorage.app',
    measurementId: 'G-6NTRD66WJT',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA24F_Pjz5TrftBkIooxl8GnmjTfdqZpG8',
    appId: '1:679860095960:web:4b8c71ad200ae396ddc0ad',
    messagingSenderId: '679860095960',
    projectId: 'groupproject-group5-a80a2',
    authDomain: 'groupproject-group5-a80a2.firebaseapp.com',
    storageBucket: 'groupproject-group5-a80a2.firebasestorage.app',
    measurementId: 'G-GECX3R1CSQ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtF-xEiGRU44NdkiRowx-b1RS7iki2P18',
    appId: '1:679860095960:ios:254dadb5bf83acc9ddc0ad',
    messagingSenderId: '679860095960',
    projectId: 'groupproject-group5-a80a2',
    storageBucket: 'groupproject-group5-a80a2.firebasestorage.app',
    iosBundleId: 'com.example.groupprojectGroup5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRENVJUxj3aOYdfnZtiEtgEgDcGyeJvxI',
    appId: '1:679860095960:android:a472549a05d475c9ddc0ad',
    messagingSenderId: '679860095960',
    projectId: 'groupproject-group5-a80a2',
    storageBucket: 'groupproject-group5-a80a2.firebasestorage.app',
  );

}